-- ── Índices en las FKs que apuntan a `entries` ──────────────────────────────
-- Postgres indexa automáticamente la PK y los UNIQUE, pero NO el lado que
-- REFERENCIA de una foreign key. Siete FKs apuntaban a `public.entries` sin un
-- índice que empezara por su columna, así que cada `delete from entries`
-- disparaba un `Seq Scan` por cada una — de la tabla ENTERA del deployment, no
-- de la temporada.
--
-- Eso venía de antes y no molestaba a nadie: el delete de `removeSeat` no
-- sostenía ningún lock mientras escaneaba. **0086 lo cambió.** Desde esa
-- migración el delete corre adentro de la sección crítica del advisory lock
-- por temporada, así que ese tiempo de scan es tiempo exacto en el que
-- `add_squad_seat` y `promote_guest` de la MISMA temporada esperan detrás. El
-- arreglo de un deadlock se había convertido, sin querer, en un serializador
-- que escala con el tamaño de la base.
--
-- Medido en la local con 201.181 filas en `pairs` (una temporada de prueba con
-- volumen, borrada después), sondeando exactamente lo que hace el chequeo de
-- integridad referencial (`select 1 from pairs where entry_a = $1 for key
-- share`), con `explain (analyze, timing)`:
--
--   sin índice .... Seq Scan on pairs ............ 13,74 ms
--   con índice .... Index Scan using pairs_entry_a_idx ... 0,085 ms
--
-- ~160x sobre UNA de las siete FKs, con una tabla que en producción va a ser
-- mucho más grande que 200k.
--
-- El costo real del delete es esa diferencia multiplicada por las siete FKs, y
-- crece lineal con la tabla; el beneficio es que la sección crítica del
-- advisory deja de depender del tamaño del deployment.
--
-- Seis índices y no siete: las dos FKs de `attendances` comparten `entry_id`
-- como columna líder, así que un solo índice cubre a las dos.
--
-- ── Costo del deploy, que también es parte del techo ────────────────────────
-- `create index` sin `concurrently` toma `ShareLock`: bloquea INSERT/UPDATE/
-- DELETE en `attendances`, `awards`, `pair_locks` y `pairs` mientras construye,
-- sobre la misma `pairs` que este comentario proyecta mucho más grande que 200k.
-- `concurrently` no se puede usar adentro de la transacción de una migración,
-- así que queda así; lo que no puede quedar es sin escribirse.
--
-- ── Lo que NO tiene guardián automático ─────────────────────────────────────
-- Hubo un preflight en el gate (`dl.fk_sin_indice()`) que chequeaba este
-- invariante y se BORRÓ, porque estaba mal en las dos direcciones y una
-- revisión lo demostró en vivo:
--   · falso NEGATIVO: su modelo era `i.indkey[0] = c.conkey[1]`, sin mirar
--     `indpred` ni `indisvalid`. Un índice PARCIAL sobre `entry_a` lo pasaba en
--     verde mientras el plan volvía a `Seq Scan` adentro de la sección crítica.
--   · falso POSITIVO: el chequeo de integridad referencial iguala TODAS las
--     columnas de la FK, no sólo la primera, así que un índice `(season_id,
--     entry_a)` sirve perfecto — y el preflight lo declaraba "sin índice" y
--     abortaba el gate sobre un schema correcto.
--   · y mira UN solo hop. El delete cascadea a `discipline_entries`, y
--     `attendances` y `discipline_teams` referencian A ESA con `discipline_id`
--     como columna líder, sin índice propio: esos chequeos también corren
--     adentro del advisory. Hoy no se paga porque el planner reusa
--     `attendances_entry_id_idx` (el que esta migración creó para OTRA FK) ya
--     que `entry_id` también está en el predicado. Es suerte, no invariante:
--     alguien que "optimice" ese índice a un compuesto reintroduce el scan.
--
-- El invariante correcto sería "toda FK alcanzable por la cascada del delete de
-- un asiento tiene un índice USABLE por su chequeo de RI", y no está
-- automatizado. Si tocás índices o agregás una tabla que referencie `entries`,
-- `discipline_entries` o `season_seed_order`, medilo a mano:
--
--   explain (analyze, timing) select 1 from <tabla> where <cols de la fk> = ... for key share;
--
-- con volumen. Y `pg_catalog` no está expuesto por PostgREST
-- (`supabase/config.toml`: `schemas = ["public", "graphql_public"]`), así que
-- esto no es testeable desde vitest ni con un tripwire de `.db.test.ts`.
create index if not exists attendances_entry_id_idx on public.attendances (entry_id);
create index if not exists awards_entry_id_idx      on public.awards (entry_id);
create index if not exists pair_locks_entry_a_idx   on public.pair_locks (entry_a);
create index if not exists pair_locks_entry_b_idx   on public.pair_locks (entry_b);
create index if not exists pairs_entry_a_idx        on public.pairs (entry_a);
create index if not exists pairs_entry_b_idx        on public.pairs (entry_b);
